In [4]:
import pandas as pd

master_list = pd.read_csv("x-ken-all.csv",usecols=[2,6,7,8],names=('郵便番号', '住所1', '住所2', '住所3'),encoding="cp932",dtype=str,na_filter=False)

In [5]:
master_list["住所"] = master_list['住所1']+master_list['住所2']+master_list['住所3']

In [6]:
# 文字数の大きい順に並び変える
master_list = master_list.sort_values(by='住所', key=lambda x: x.str.len(), ascending=False)

In [7]:
master_list.drop(['住所1', '住所2', '住所3'], axis=1, inplace=True)

In [8]:
master_list

          郵便番号                                 住所
31071  3306022  埼玉県さいたま市中央区新都心明治安田生命さいたま新都心ビル　２２階
31082  3306033  埼玉県さいたま市中央区新都心明治安田生命さいたま新都心ビル　３３階
31073  3306024  埼玉県さいたま市中央区新都心明治安田生命さいたま新都心ビル　２４階
31074  3306025  埼玉県さいたま市中央区新都心明治安田生命さいたま新都心ビル　２５階
31075  3306026  埼玉県さいたま市中央区新都心明治安田生命さいたま新都心ビル　２６階
...        ...                                ...
40536  1140000                              東京都北区
32742  3350000                              埼玉県蕨市
46869  9591200                              新潟県燕市
61820  5013200                              岐阜県関市
38226  1050000                              東京都港区

[127448 rows x 2 columns]

In [9]:
import jaconv
# 数字を漢数字に変換して二桁の場合は間に"十"を挿入する関数
def convert_to_kanji_with_ju(num_str):
    kanji = jaconv.z2h(num_str, digit=True, ascii=True, kana=False)
    if len(kanji) == 2 and kanji[0] == "一":
        kanji = kanji[1]
    if len(kanji) == 2:
        kanji = kanji[0] + "十" + kanji[1]
    return kanji

# 住所の数字を漢数字に変換して二桁の場合は間に"十"を挿入する
salon_list["住所"] = salon_list["住所"].apply(lambda x: ''.join(convert_to_kanji_with_ju(i) for i in x))

In [10]:
master_list

          郵便番号                                 住所
31071  3306022  埼玉県さいたま市中央区新都心明治安田生命さいたま新都心ビル 22階
31082  3306033  埼玉県さいたま市中央区新都心明治安田生命さいたま新都心ビル 33階
31073  3306024  埼玉県さいたま市中央区新都心明治安田生命さいたま新都心ビル 24階
31074  3306025  埼玉県さいたま市中央区新都心明治安田生命さいたま新都心ビル 25階
31075  3306026  埼玉県さいたま市中央区新都心明治安田生命さいたま新都心ビル 26階
...        ...                                ...
40536  1140000                              東京都北区
32742  3350000                              埼玉県蕨市
46869  9591200                              新潟県燕市
61820  5013200                              岐阜県関市
38226  1050000                              東京都港区

[127448 rows x 2 columns]

In [11]:
salon_list = pd.read_excel(r"取り込むファイル\DMリスト_最新_20230804_123031_20230804_130245.xlsx",dtype=str,na_filter=False)

In [12]:
salon_list

,管理,美容室名,郵便番号,検索用住所,住所,電話番号
0,2023-07-31 00:00:00,アグ ヘアー イコロ 札幌平岸店(Agu hair ikoro),,北海道札幌市豊平区平岸２条８-２-６,北海道札幌市豊平区平岸２条８-２-６ 第２松井ビル１F,
1,2023-07-31 00:00:00,モッズヘアメン 札幌月寒店(mod's hair men),,北海道札幌市豊平区月寒中央通９－３－３７,北海道札幌市豊平区月寒中央通９－３－３７ CBSビル１F,
2,2023-07-31 00:00:00,バリエ ホテル日航札幌店(VARIE),,北海道札幌市中央区北５条西２丁目,北海道札幌市中央区北５条西２丁目-５JRタワーホテル日航札幌 ２２F,
3,2023-07-31 00:00:00,イリ(Ili),,北海道札幌市中央区南２条西３丁目１３,北海道札幌市中央区南２条西３丁目１３－２ パレードビル２階,
4,2023-07-31 00:00:00,アーサス バイ ヘッドライト 岩見沢店(ursus by HEADLIGHT),,北海道岩見沢市南町８条２‐２‐１６,北海道岩見沢市南町８条２‐２‐１６,
...,...,...,...,...,...,...
1611,2023-07-31 00:00:00,ブルームk2 浮島通り店(bloom k2),,沖縄県那覇市松尾２－５－１,沖縄県那覇市松尾２－５－１ ２Ｆ,
1612,2023-07-31 00:00:00,スタイルボーンタイムスバーチ(Styleborn×BURCH),,沖縄県中頭郡北谷町北前１丁目18-3,沖縄県中頭郡北谷町北前１丁目18-3 名城ビル1F,
1613,2023-07-31 00:00:00,ウルズ(ULUZZ..),,沖縄県那覇市銘苅１－１０－８,沖縄県那覇市銘苅１－１０－８ 新都心ベースビル ４－Ｂ,
1614,2023-07-31 00:00:00,デイジー(daisy),,沖縄県国頭郡本部町渡久地１８０,沖縄県国頭郡本部町渡久地１８０,
1615,2023-07-31 00:00:00,ロジャー(Roger),,沖縄県うるま市赤道１６－２,沖縄県うるま市赤道１６－２,

In [13]:
import jaconv
# 数字を漢数字に変換して二桁の場合は間に"十"を挿入する関数
def convert_to_kanji_with_ju(num_str):
    kanji = jaconv.z2h(num_str, digit=True, ascii=True, kana=False)
    if len(kanji) == 2 and kanji[0] == "一":
        kanji = kanji[1]
    if len(kanji) == 2:
        kanji = kanji[0] + "十" + kanji[1]
    return kanji

# 住所の数字を漢数字に変換して二桁の場合は間に"十"を挿入する
salon_list["住所"] = salon_list["住所"].apply(lambda x: ''.join(convert_to_kanji_with_ju(i) for i in x))

In [14]:
salon_list

,管理,美容室名,郵便番号,検索用住所,住所,電話番号
0,2023-07-31 00:00:00,アグ ヘアー イコロ 札幌平岸店(Agu hair ikoro),,北海道札幌市豊平区平岸２条８-２-６,北海道札幌市豊平区平岸2条8-2-6 第2松井ビル1F,
1,2023-07-31 00:00:00,モッズヘアメン 札幌月寒店(mod's hair men),,北海道札幌市豊平区月寒中央通９－３－３７,北海道札幌市豊平区月寒中央通9-3-37 CBSビル1F,
2,2023-07-31 00:00:00,バリエ ホテル日航札幌店(VARIE),,北海道札幌市中央区北５条西２丁目,北海道札幌市中央区北5条西2丁目-5JRタワーホテル日航札幌 22F,
3,2023-07-31 00:00:00,イリ(Ili),,北海道札幌市中央区南２条西３丁目１３,北海道札幌市中央区南2条西3丁目13-2 パレードビル2階,
4,2023-07-31 00:00:00,アーサス バイ ヘッドライト 岩見沢店(ursus by HEADLIGHT),,北海道岩見沢市南町８条２‐２‐１６,北海道岩見沢市南町8条2‐2‐16,
...,...,...,...,...,...,...
1611,2023-07-31 00:00:00,ブルームk2 浮島通り店(bloom k2),,沖縄県那覇市松尾２－５－１,沖縄県那覇市松尾2-5-1 2F,
1612,2023-07-31 00:00:00,スタイルボーンタイムスバーチ(Styleborn×BURCH),,沖縄県中頭郡北谷町北前１丁目18-3,沖縄県中頭郡北谷町北前1丁目18-3 名城ビル1F,
1613,2023-07-31 00:00:00,ウルズ(ULUZZ..),,沖縄県那覇市銘苅１－１０－８,沖縄県那覇市銘苅1-10-8 新都心ベースビル 4-B,
1614,2023-07-31 00:00:00,デイジー(daisy),,沖縄県国頭郡本部町渡久地１８０,沖縄県国頭郡本部町渡久地180,
1615,2023-07-31 00:00:00,ロジャー(Roger),,沖縄県うるま市赤道１６－２,沖縄県うるま市赤道16-2,

In [ ]:
############################### 部分一の対象が逆(containは使えない) ####################################
# salon_listの郵便番号カラムが空白の場合にmaster_listの住所カラムと一致するものに対して、対応するmaster_listの郵便番号を代入
for index, row in salon_list.iterrows():
    if row['郵便番号'] == '':
        address = row['住所']
        matched_row = master_list[master_list['住所'].str.contains(address)]
        if not matched_row.empty:
            salon_list.at[index, '郵便番号'] = matched_row.iloc[0]['郵便番号']
            print(salon_list.at[index, '郵便番号'])
            

print(salon_list)

In [3]:
import pandas as pd
import re

salon_list = pd.read_excel(r"取り込むファイル\DMリスト_最新_20230804_123031_20230804_130245.xlsx",dtype=str,na_filter=False)

# 数字を漢数字に変換する関数
def number_to_kanji(number_str):
    kanji_digits = ["〇", "一", "二", "三", "四", "五", "六", "七", "八", "九"]
    kanji_tens = ["", "十", "百", "千", "万"]  # 十の位以上に対応するように修正

    numbers = re.findall(r'\d+', number_str)
    for number in numbers:
        if int(number) == 0:
            kanji_result = kanji_digits[0]
        else:
            kanji_result = ""
            digit_count = 0
            num = int(number)
            while num > 0:
                digit = num % 10
                if digit != 0:
                    # 二桁目が"1"の場合は"十"を挿入した後に"一"を削除
                    if digit == 1 and digit_count == 1:
                        kanji_result = kanji_tens[digit_count] + kanji_result
                    else:
                        kanji_result = kanji_digits[digit] + kanji_tens[digit_count] + kanji_result
                num //= 10
                digit_count += 1

        number_str = number_str.replace(number, kanji_result)

    return number_str

# 住所の数字を漢数字に変換
salon_list["住所"] = salon_list["住所"].apply(number_to_kanji)

print(salon_list["住所"])

0              北海道札幌市豊平区平岸二条八-二-六　第二松井ビル一F
1             北海道札幌市豊平区月寒中央通九－三－三７　CBSビル一F
2       北海道札幌市中央区北五条西二丁目-五JRタワーホテル日航札幌 二二F
3            北海道札幌市中央区南二条西三丁目１三－二　パレードビル二階
4                        北海道岩見沢市南町八条二‐二‐十六
                       ...
1611                      沖縄県那覇市松尾二－五－一　二Ｆ
1612             沖縄県中頭郡北谷町北前一丁目十八-三　名城ビル一F
1613           沖縄県那覇市銘苅一－一０－八 新都心ベースビル 四－Ｂ
1614                      沖縄県国頭郡本部町渡久地一百八十
1615                         沖縄県うるま市赤道十六－二
Name: 住所, Length: 1616, dtype: object

In [8]:
#################################### 完成版　2023/08/06 ################################################

import pandas as pd
import re

salon_list = pd.read_excel(r"取り込むファイル\DMリスト_最新_20230804_123031_20230804_130245.xlsx",dtype=str,na_filter=False)

# 数字を漢数字に変換する関数
def number_to_kanji(number_str):
    # 漢数字として使う文字のリストを定義
    kanji_digits = ["〇", "一", "二", "三", "四", "五", "六", "七", "八", "九"]
    kanji_tens = ["", "十", "百", "千", "万", "億"]  # 十の位以上に対応するように修正

    # 漢数字に変換しない住所リストを定義
    not_convert_list = [
        "北海道旭川市",
        "北海道江別市",
        "夕張郡長沼町",
        "雨竜郡妹背牛町",
        "雨竜郡秩父別町",
        "上川郡鷹栖町",
        "上川郡東神楽町",
        "上川郡東川町",
        "喜多方市",
        "空知郡南幌町",
        "和賀郡西和賀町",
        "中央アエル",
        "住友生命仙台中央ビル"
    ]

    # 住所が漢数字に変換しないリストに含まれている場合は変換を行わない
    for addr in not_convert_list:
        if addr in number_str:
            return number_str

    # 数字を漢数字に変換する関数
    def replace_digit(match):
        number = match.group(0)
        if len(number) == 1:
            # 一桁の場合はそのまま漢数字に変換
            return kanji_digits[int(number)]
        else:
            # 二桁以上の場合は各桁を漢数字に変換
            kanji_result = ""
            digit_count = 0
            num = int(number)
            while num > 0:
                digit = num % 10
                if digit != 0:
                    # 二桁目が"1"の場合は"十"を挿入した後に"一"を削除
                    if digit == 1 and digit_count == 1 and len(kanji_result) > 0 and kanji_result[-1] == "十":
                        kanji_result = kanji_tens[digit_count]
                    else:
                        kanji_result = kanji_digits[digit] + kanji_tens[digit_count] + kanji_result
                num //= 10
                digit_count += 1

            # 数字が2桁以上の場合は先頭の"一"を削除
            kanji_result = kanji_result.replace("一", "", 1)
            return kanji_result

    # 数字の右に"F"があれば"階"に置換
    number_str = number_str.replace("F", "階")
    number_str = number_str.replace("Ｆ", "階")

    # 正規表現を使って、数字を漢数字に置き換える（数字の右に"F"がある場合は変換しない）
    return re.sub(r'\d+(?!階)', replace_digit, number_str)

# 住所の数字を漢数字に変換
salon_list["住所"] = salon_list["住所"].apply(number_to_kanji)

print(salon_list)

                       管理                                     美容室名 郵便番号  \
0     2023-07-31 00:00:00         アグ ヘアー イコロ 札幌平岸店(Agu hair ikoro)
1     2023-07-31 00:00:00            モッズヘアメン 札幌月寒店(mod's hair men)
2     2023-07-31 00:00:00                      バリエ ホテル日航札幌店(VARIE)
3     2023-07-31 00:00:00                                  イリ(Ili)
4     2023-07-31 00:00:00  アーサス バイ ヘッドライト 岩見沢店(ursus by HEADLIGHT)
...                   ...                                      ...  ...
1611  2023-07-31 00:00:00                   ブルームk2 浮島通り店(bloom k2)
1612  2023-07-31 00:00:00          スタイルボーンタイムスバーチ(Styleborn×BURCH)
1613  2023-07-31 00:00:00                             ウルズ(ULUZZ..)
1614  2023-07-31 00:00:00                              デイジー(daisy)
1615  2023-07-31 00:00:00                              ロジャー(Roger)

                     検索用住所                                   住所 電話番号
0       北海道札幌市豊平区平岸２条８-２-６         北海道札幌市豊平区平岸二条八-二-六　第二松井ビル１階
1     北海道札幌市豊平区月寒中央通９－３－３７       北海道札幌市豊平区月寒中央通九－三－三十七　CBSビル１階
2         北海道札幌市中央区北５条西２丁目  北海道札幌市中央区北五条西二丁目-五JRタワーホテル日航札幌 二２階
3       北海道札幌市中央区南２条西３丁目１３       北海道札幌市中央区南二条西三丁目十三－二　パレードビル２階
4       北海道岩見沢市南町８条２‐２‐１６                    北海道岩見沢市南町八条二‐二‐十六
...                    ...                                  ...  ...
1611         沖縄県那覇市松尾２－５－１                    沖縄県那覇市松尾二－五－一　２階
1612    沖縄県中頭郡北谷町北前１丁目18-3           沖縄県中頭郡北谷町北前一丁目十八-三　名城ビル1階
1613        沖縄県那覇市銘苅１－１０－８          沖縄県那覇市銘苅一－十－八 新都心ベースビル 四－Ｂ
1614      沖縄県国頭郡本部町渡久地１８０                      沖縄県国頭郡本部町渡久地百八十
1615        沖縄県うるま市赤道１６－２                        沖縄県うるま市赤道十六－二

[1616 rows x 6 columns]

In [ ]:
salon_list

In [49]:
from tqdm import tqdm

# tqdmを使ってプログレスバーを追加
for index, row in tqdm(salon_list.iterrows(), total=len(salon_list)):
    if row['郵便番号'] == '':
        address = row['住所']
        matched_row = master_list[master_list['住所'].str.contains(address)]
        if not matched_row.empty:
            salon_list.at[index, '郵便番号'] = matched_row.iloc[0]['郵便番号']


print(salon_list)
# 結果をExcelファイルにエクスポート
output_file = 'result.xlsx'
salon_list.to_excel(output_file, index=False)

 18%|█▊        | 288/1616 [00:10<00:50, 26.40it/s]C:\Users\kaihatsu\AppData\Local\Temp\ipykernel_19572\1971080888.py:7: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  matched_row = master_list[master_list['住所'].str.contains(address)]
100%|██████████| 1616/1616 [01:02<00:00, 26.02it/s]

                       管理                                     美容室名 郵便番号  \
0     2023-07-31 00:00:00         アグ ヘアー イコロ 札幌平岸店(Agu hair ikoro)
1     2023-07-31 00:00:00            モッズヘアメン 札幌月寒店(mod's hair men)
2     2023-07-31 00:00:00                      バリエ ホテル日航札幌店(VARIE)
3     2023-07-31 00:00:00                                  イリ(Ili)
4     2023-07-31 00:00:00  アーサス バイ ヘッドライト 岩見沢店(ursus by HEADLIGHT)
...                   ...                                      ...  ...
1611  2023-07-31 00:00:00                   ブルームk2 浮島通り店(bloom k2)
1612  2023-07-31 00:00:00          スタイルボーンタイムスバーチ(Styleborn×BURCH)
1613  2023-07-31 00:00:00                             ウルズ(ULUZZ..)
1614  2023-07-31 00:00:00                              デイジー(daisy)
1615  2023-07-31 00:00:00                              ロジャー(Roger)

                     検索用住所                                   住所 電話番号
0       北海道札幌市豊平区平岸２条８-２-６         北海道札幌市豊平区平岸２条８-２-６　第２松井ビル１F
1     北海道札幌市豊平区月寒中央通９－３－３７        北海道札幌市豊平区月寒中央通９－３－３７　CBSビル１F
2         北海道札幌市中央区北５条西２丁目  北海道札幌市中央区北５条西２丁目-５JRタワーホテル日航札幌 ２２F
3       北海道札幌市中央区南２条西３丁目１３       北海道札幌市中央区南２条西３丁目１３－２　パレードビル２階
4       北海道岩見沢市南町８条２‐２‐１６                    北海道岩見沢市南町８条２‐２‐１６
...                    ...                                  ...  ...
1611         沖縄県那覇市松尾２－５－１                    沖縄県那覇市松尾２－５－１　２Ｆ
1612    沖縄県中頭郡北谷町北前１丁目18-3           沖縄県中頭郡北谷町北前１丁目18-3　名城ビル1F
1613        沖縄県那覇市銘苅１－１０－８         沖縄県那覇市銘苅１－１０－８ 新都心ベースビル ４－Ｂ
1614      沖縄県国頭郡本部町渡久地１８０                      沖縄県国頭郡本部町渡久地１８０
1615        沖縄県うるま市赤道１６－２                        沖縄県うるま市赤道１６－２

[1616 rows x 6 columns]

In [50]:
# tqdmを使ってプログレスバーを追加
for index, row in tqdm(salon_list.iterrows(), total=len(salon_list)):
    if row['郵便番号'] == '':
        address = row['住所']
        matched_row = master_list[master_list['住所'].apply(lambda x: address in x)]
        if not matched_row.empty:
            salon_list.at[index, '郵便番号'] = matched_row.iloc[0]['郵便番号']
            print(salon_list.at[index, '郵便番号'])

# 結果をExcelファイルにエクスポート
output_file = 'result.xlsx'
salon_list.to_excel(output_file, index=False)

100%|██████████| 1616/1616 [00:28<00:00, 57.38it/s]